### ISSUE TITLE
Config file resetting after reloading / restarting the server

### ISSUE THREAD

**Issue by NotToBlame** [EncryptSL/CENSOR-RELOADED-ISSUES#1]
Tried taking out and adding in some additional words onto the config.yml file but after every time I reload it changes back to what it had before

**Comment by EncryptSL** [comment]
Plugin Version, and server version ?

**Comment by NotToBlame** [comment]
> Plugin Version, and server version ?

3.7DevBata and also tried with 3.9.4 Latest Verson on a 1.12.2 Server

**Comment by NotToBlame** [comment]
Just tried manually restarting the server and the issue remains. Configuration goes back to what it was originally with the original words in there. I couldn't quite understand using v3.9.4 with the badwords.txt as the original blacklisted words were still there

**Comment by EncryptSL** [comment]
When you are using new version, 3.9.4 - No need restarting because txt file reading in realtime and no saving into memory. badwords.txt have default pre-filled words set.

This working normally, just write a word into badwords.txt. But you must press save ctrl+s.

You must write another badword on new line.
Example: of badwords.txt
fuck
dick <- another new word
pussy <- another new word ....

**Comment by EncryptSL** [comment]
@NotToBlame In new version 3.9.5 is i think fixed.
