### ISSUE TITLE
Size of the Plugin

### ISSUE THREAD

**Issue by HyperSetups** [EncryptSL/CENSOR-RELOADED-ISSUES#10]
Hello.

I deleted the template because this is a question.

I accidently downloaded CensorReloaded 4.1.3 and it was around 7 MB. But latest version is just 40 KB. What did you deleted or added, I couldn't understand?

**Comment by EncryptSL** [comment]
Older version of my plugin use another concept of maven. Because now plugin have including source of metrics for Bstats. From maven repositories, Included into plugin. 

If I didn't include it, you would have to manually download other necessary files for the feature.

Big Size of plugin is because i not implementing minifying.
In next version i will try created smaller file size.
